52

diff --git a/.github/workflows/ci_terragrunt.yml b/.github/workflows/ci_terragrunt.yml
--- a/.github/workflows/ci_terragrunt.yml
+++ b/.github/workflows/ci_terragrunt.yml
@@ -93,21 +93,28 @@ jobs:
       # - name: Install jq
       #   run: sudo apt-get install jq
         
-      - name: Load Terragrunt Config
-        id: load-terragrunt-config
+      - name: Load Terragrunt and Terraform Versions
         run: |
           export TERRAGRUNT_VERSION=$(terragrunt locals | jq -r '.terragrunt_version')
           export TERRAFORM_VERSION=$(terragrunt locals | jq -r '.terraform_version')
-        working-directory: '${{ env.tf_working_dir }}'
-      
-      - name: Set Terragrunt and Terraform Versions
-        run: |
-          echo "Using Terragrunt version: $TERRAGRUNT_VERSION"
+
+          echo "Terragrunt Version: $TERRAGRUNT_VERSION"
+          echo "Terraform Version: $TERRAFORM_VERSION"
+
+          if [ -z "$TERRAGRUNT_VERSION" ]; then
+            echo "Error: Terragrunt version not set!"
+            exit 1
+          fi
+
+          if [ -z "$TERRAFORM_VERSION" ]; then
+            echo "Error: Terraform version not set!"
+            exit 1
+          fi
+
           tgenv install $TERRAGRUNT_VERSION
           tgenv use $TERRAGRUNT_VERSION
           terragrunt --version
-      
-          echo "Using Terraform version: $TERRAFORM_VERSION"
+
           tfenv install $TERRAFORM_VERSION
           tfenv use $TERRAFORM_VERSION
           terraform --version
